baseURL = 'https://wangyjer.github.io/'
languageCode = 'en-us'
title = ''
theme = "PaperMod"
[taxonomies]
  tag = "tags"
  category = "categories"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "博客"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "categories"
    name = "分类"
    url = "/categories/"
    weight = 30

  [[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "/tags/"
    weight = 40

  [[menu.main]]
    identifier = "archive"
    name = "存档"
    url = "/archive/"
    weight = 50

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 60
    
[params.homeInfoParams]
  Title = "记录美好生活！"
  Content = "点滴的记录犹如涓涓流水，终有一日会流入那山间的湖泊。我们在湖泊旁驻足欣赏，感受人生的美好！"